version: '2'

networks:
  default:
    external:
      name: nginx-proxy

services:
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yourpasswordhere
      - VIRTUAL_PORT=8086
    ports:
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
  grafana:
    image: grafana/grafana
    environment:
      - VIRTUAL_HOST=yourhostnamehere.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=yourhostnamehere.como
      - LETSENCRYPT_EMAIL=youremailhere@gmail.com
    volumes:
      - /var/lib/grafana
