version: '2'

networks:
  nginx-proxy:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "~/certs:/etc/nginx/certs"
    networks:
      - nginx-proxy
  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "~/certs:/etc/nginx/certs:rw"
    volumes_from:
      - "nginx-proxy"
    networks:
      - nginx-proxy
  collectd:
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=yourpassword
      - VIRTUAL_PORT=8086
    ports:
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro
    networks:
      - nginx-proxy
  grafana:
    image: grafana/grafana
    environment:
      - VIRTUAL_HOST=yourhostname.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=yourhostname.com
      - LETSENCRYPT_EMAIL=youremail
    volumes:
      - /var/lib/grafana
    networks:
      - nginx-proxy
